version: '3'

services:
  mongo-twitter-test-job:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    networks:
      - test

  test_job:
    build: ${PWD}/job
    command: python -m unittest test.test_twitterapi test.test_util
    volumes:
      - ${PWD}/job:/app
    depends_on:
      - mongo-twitter-test-job
    environment: 
      MONGO_ROOT_USERNAME: "admin"
      MONGO_ROOT_PASSWORD: "root"
      MONGO_HOST: "mongo-twitter-test-job"
    networks:
      - test

  mongo-twitter-test-api:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    networks:
      - test
  
  test_api:
    build: ${PWD}/api
    command: python -m unittest test.test_api
    volumes:
      - ${PWD}/api:/app
    depends_on:
      - mongo-twitter-test-api
    environment: 
      MONGO_ROOT_USERNAME: "admin"
      MONGO_ROOT_PASSWORD: "root"
      MONGO_HOST: "mongo-twitter-test-api"
      FLASK_APP: "/app/app.py"
    networks:
      - test

networks:
  test:
