version: '3'

services:
  mongo-twitter-test:
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    networks:
      - test

  test_job:
    build: ${PWD}/job
    command: python -m unittest test.twitterapi_test test.util_test
    volumes:
      - ${PWD}/job:/app
    depends_on:
      - mongo-twitter-test
    environment: 
      MONGO_ROOT_USERNAME: "admin"
      MONGO_ROOT_PASSWORD: "root"
      MONGO_HOST: "mongo-twitter-test"
    networks:
      - test

networks:
  test:
