{
 "title": "Monitorações",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requests/s com sucesso",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s]))",
     "legendFormat": "Total de requests/s"
    }
   ]
  },
  {
   "title": "Requests/s com erro",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=~\"5..\"}[30s]))",
     "legendFormat": "Total de requests/s"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta de requests com sucesso",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(\n  flask_http_request_duration_seconds_sum{status=\"200\"}[30s]\n))\n /\nsum(rate(\n  flask_http_request_duration_seconds_count{status=\"200\"}[30s]\n))",
     "legendFormat": "Tempo médio de resposta"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"api:5000\"}"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"api:5000\"}[30s])"
    }
   ]
  }
 ]
}